# * 标有 * 的设置是高级设置，不会出现在 Streamlit 页面中，只能在 config.py 中手动修改
version: "2.1.2"
## ======================== 基本设置 ======================== ##
# API 设置
api:
  key: 'sk-4b8FoFAjxtSQihUDDhoD5pvOlq6mwlMljtWDTMwTGTJZ7oPU'
  base_url: 'https://api.302.ai'
  model: 'gemini-2.0-flash-exp'

# 语言设置，写入提示词，可以用自然语言描述
target_language: 'English'

# 是否在转录前进行人声分离
demucs: true

whisper:
  # ["medium", "large-v3", "large-v3-turbo"]. 注意：对于中文模型将强制使用 Belle/large-v3
  model: 'large-v3'
  # Whisper 指定识别语言 [en, zh, ...]
  language: 'zh'
  detected_language: 'zh'

# 视频分辨率 [0x0, 640x360, 1920x1080] 0x0 会生成一个 0 秒的黑色视频占位符
resolution: '1920x1080'

## ======================== 高级设置 ======================== ##
# *下载 YouTube 视频的默认分辨率 [360, 1080, best]
ytb_resolution: '1080'

subtitle:
  # *每行字幕的最大字符长度
  max_length: 75
  # *翻译后的字幕比源字幕略大，影响字幕分割的参考长度
  target_multiplier: 1.2

# *总结长度，如果使用本地 LLM 设置为 2k
summary_length: 8000

# *LLM 多线程访问数量，如果使用本地 LLM 设置为 1
max_workers: 4
# *第一次粗分的最大字数，低于 18 会切得太细影响翻译，高于 22 太长会导致后续字幕分割难以对齐
max_split_length: 20

# *是否进行反思翻译，false 只进行一次翻译
reflect_translate: true

# *是否在提取专业术语后、翻译前暂停，让用户手动调整术语表 output\log\terminology.json
pause_before_translate: false

## ======================== 配音设置 ======================== ##
# TTS 选择 [sf_fish_tts, openai_tts, gpt_sovits, azure_tts, fish_tts, edge_tts, custom_tts]
tts_method: 'openai_tts'

# SiliconFlow FishTTS
sf_fish_tts:
  # SiliconFlow API key
  api_key: 'sk-tyieqmvflleduiytabgvgsnhynxsotfiswrfjjyiqxsththt'
  # 仅用于 "preset" 模式
  voice: 'anna'
  # *仅用于 "custom" 模式，不要手动设置
  custom_name: 'd9605603'
  voice_id: 'speech:d9605603:cm4cdszs3035zj9077618cx7c:csuhylijcjslesrslffe'
  # preset, custom, dynamic
  mode: "dynamic"

# OpenAI TTS-1 API 配置, 仅限 302.ai API
openai_tts:
  api_key: 'sk-4b8FoFAjxtSQihUDDhoD5pvOlq6mwlMljtWDTMwTGTJZ7oPU'
  voice: 'alloy'

# Azure 配置, 仅限 302.ai API
azure_tts:
  api_key: 'YOUR_302_API_KEY'
  voice: 'zh-CN-YunfengNeural'

# FishTTS 配置, 仅限 302.ai API
fish_tts:
  api_key: 'YOUR_302_API_KEY'
  character: 'AD学姐'
  character_id_dict:
    'AD学姐': '7f92f8afb8ec43bf81429cc1c9199cb1'
    '丁真': '54a5170264694bfc8e9ad98df7bd89c3'

# Edge TTS 配置
edge_tts:
  voice: 'zh-CN-XiaoxiaoNeural'

# SoVITS 配置
gpt_sovits:
  character: 'Huanyuv2'
  refer_mode: 3

# *音频速度范围
speed_factor:
  min: 1
  accept: 1.2 # 可以接受的最大速度
  max: 1.4

# *合并音频配置
min_subtitle_duration: 2.5 # 最小字幕出现时间 会强制扩展
min_trim_duration: 3.5 # 小于这个值的字幕不会切割
tolerance: 1.5 # 允许向后延申的时间

# 音量设置
dub_volume: 1.5  # *配音音频音量（1.5 = 150%，大多数原始配音音频相对较安静）






## ======================== 附加设置 请勿修改 ======================== ##
# Whisper 模型目录
model_dir: './_model_cache'

# 支持的上传视频格式
allowed_video_formats:
- 'mp4'
- 'mov'
- 'avi'
- 'mkv'
- 'flv'
- 'wmv'
- 'webm'

allowed_audio_formats:
- 'wav'
- 'mp3'
- 'flac'
- 'm4a'

# 支持返回 JSON 格式的 LLM
llm_support_json:
- 'gpt-4o'
- 'gpt-4o-mini'
- 'gemini-2.0-flash-exp'
- 'deepseek-coder'

# 存在问题
# - 'Qwen/Qwen2.5-72B-Instruct'
# - 'Qwen/Qwen2.5-Coder-32B-Instruct'
# - 'Qwen/Qwen2.5-Chat-72B-Instruct-128K'

# Spacy 模型
spacy_model_map:
  en: 'en_core_web_md'
  ru: 'ru_core_news_md'
  fr: 'fr_core_news_md'
  ja: 'ja_core_news_md'
  es: 'es_core_news_md'
  de: 'de_core_news_md'
  it: 'it_core_news_md'
  zh: 'zh_core_web_md'

# 使用空格作为分隔符的语言
language_split_with_space:
- 'en'
- 'es'
- 'fr'
- 'de'
- 'it'
- 'ru'

# 不使用空格作为分隔符的语言
language_split_without_space:
- 'zh'
- 'ja'
